name: Prettier Format Check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  format:
    name: Check Prettier Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # or whatever version you're using

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm prettier --check .
